version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  createdb:
    image: postgres
    depends_on:
      - db
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    command: ["createdb", "offerfit_development", "-h", "db", "-U", "${POSTGRES_USER}"]
